# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'Wallet/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/Wallet/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'



- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)/drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureAppServiceConnection'
    appName: 'app-wallet-cwu'
    package: '$(Pipeline.Workspace)/drop/Wallet-0.0.1-SNAPSHOT.jar'
    appType: 'webAppLinux'